### ISSUE TITLE
Populate Dictionary values in user config?

### ISSUE THREAD

**Issue by jcamozzi** [audreyr/cookiecutter#1046]
* Cookiecutter version: 1.6
* Template project url: n/a
* Python version: 2.7
* Operating System: MacOs High Sierra

### Description:

I know I can define dictionary values the cookiecutter.json file, but I'm not sure how I can do this in the userconfig.yml file — nor am I sure it's possible. I may just not know the format (there's nothing in the docs about this). default_context seems to just allow key/value pairs, and trying use yaml-based nesting fails.

So, is there a way I can pre-propulate dictionary values in the default_context: of a user config?

### What I've run:

.json example:

```
{
    "collection": {
        "sub-value-1" : {
             "sub-key-1": "somevalue"
         },
         "sub-value-2": {
              "sub-key-2": "othervalue"
         }
    }
}
```
yml attempt:

```
default_context:
  collection:
    sub-value-1:
        sub-key-1: "new value"
        sub-key-additional: "something I added"
```

(I've also tried using curly braces in the yml context, which doesn't work at all)

Thanks for your help!
