### ISSUE TITLE
Document how to do conditional files/directories

### ISSUE THREAD

**Issue by pydanny** [audreyr/cookiecutter#723]
In the [advanced_usage.rst](https://github.com/audreyr/cookiecutter/blob/master/docs/advanced_usage.rst) document we should document the following techniques:

1. By default have all the files, then use https://github.com/pydanny/cookiecutter-django/blob/master/hooks/post_gen_project.py#L163-L165 to remove those things not needed. (works everywhere)
2. Use logic in directory names to set whether or not something is created. (Only works in Linux/OSX)

**Comment by jamesbassett** [comment]
Yeah I needed this a while ago, and came up with an approach similar to 1:

- feature flags (choice) in `cookiecutter.json`
- templated `manifest.yml` file that lists all the files that should be removed if a feature is disabled
- post hook to read manifest and delete relevant files

`cookiecutter.json`
```json
{
    "project": "my-project",
    "feature1": [true, false],
    "feature2": [true, false]
}
```

`manifest.yml` (templated file in cookiecutter)
```yaml
features:
  - name: feature1
    enabled: {{cookiecutter.feature1|lower}}
    resources:
      - path/to/file/{{cookiecutter.project}}/Feature1a.txt
      - path/to/file/{{cookiecutter.project}}/Feature1b.txt

  - name: feature2
    enabled: {{cookiecutter.feature2|lower}}
    resources:
      - path/to/file/{{cookiecutter.project}}/Feature2.txt
```

`post_gen_project.py`
```python
#!/usr/bin/env python
import os
import shutil
import yaml

MANIFEST = "manifest.yml"


def delete_resources_for_disabled_features():
    with open(MANIFEST) as manifest_file:
        manifest = yaml.load(manifest_file)
        for feature in manifest['features']:
            if not feature['enabled']:
                print "removing resources for disabled feature {}...".format(feature['name'])
                for resource in feature['resources']:
                    delete_resource(resource)
    print "cleanup complete, removing manifest..."
    delete_resource(MANIFEST)


def delete_resource(resource):
    if os.path.isfile(resource):
        print "removing file: {}".format(resource)
        os.remove(resource)
    elif os.path.isdir(resource):
        print "removing directory: {}".format(resource)
        shutil.rmtree(resource)

if __name__ == "__main__":
    delete_resources_for_disabled_features()

```
